[package]
name = "ttt"
version = "0.0.0"
description = "another hardware device debug tool "
authors = ["ly"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "x_box_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2.0.3", features = [] }

[dependencies]
tauri = { version = "2.1.1", features = [] }
tauri-plugin-shell ="2.0.2"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
serde_with = {version = "3.11.0",features = ["base64"] }
socket2 = "0.5.7"
tokio = { version ="1.41.1", features = ["full"] }
thiserror = "2.0.3"
chrono = {version="0.4.38",features= ["serde"] }
local-ip-address = "0.6.3"

[target.'cfg(not(target_arch = "ios"))'.dependencies]
serialport =  {version="4.6.0",features= ["serde"] }

rumqttc = "0.24.0"
bytes="1.8.0"
crc = "3.2.1"
